framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 20
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            scheduler_main: 'scheduler://main'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            'App\Message\EmailQueueMessage': async
            'App\Message\CleanupExpiredTransfersMessage': async
