<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260409170003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE recipient_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE transfer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE transfer_file_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE recipient (id INT NOT NULL, token VARCHAR(64) NOT NULL, email TEXT NOT NULL, downloaded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_reminder_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, password_hash TEXT DEFAULT NULL, pending_password_encrypted TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, transfer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6804FB495F37A13B ON recipient (token)');
        $this->addSql('CREATE INDEX IDX_6804FB49537048AF ON recipient (transfer_id)');
        $this->addSql('CREATE TABLE transfer (id INT NOT NULL, token VARCHAR(64) NOT NULL, owner_token VARCHAR(64) NOT NULL, reference VARCHAR(9) NOT NULL, sender_email TEXT DEFAULT NULL, sender_name VARCHAR(255) DEFAULT NULL, encrypted_message TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, tus_upload_key VARCHAR(64) DEFAULT NULL, password_hash TEXT DEFAULT NULL, pending_password_encrypted TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4034A3C05F37A13B ON transfer (token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4034A3C0AFAE941C ON transfer (owner_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4034A3C0AEA34913 ON transfer (reference)');
        $this->addSql('CREATE TABLE transfer_file (id INT NOT NULL, original_name VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) DEFAULT NULL, file_size BIGINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, transfer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B46A1A72537048AF ON transfer_file (transfer_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE recipient ADD CONSTRAINT FK_6804FB49537048AF FOREIGN KEY (transfer_id) REFERENCES transfer (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transfer_file ADD CONSTRAINT FK_B46A1A72537048AF FOREIGN KEY (transfer_id) REFERENCES transfer (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE recipient_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE transfer_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE transfer_file_id_seq CASCADE');
        $this->addSql('ALTER TABLE recipient DROP CONSTRAINT FK_6804FB49537048AF');
        $this->addSql('ALTER TABLE transfer_file DROP CONSTRAINT FK_B46A1A72537048AF');
        $this->addSql('DROP TABLE recipient');
        $this->addSql('DROP TABLE transfer');
        $this->addSql('DROP TABLE transfer_file');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
