# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    tus_upload_path: '%kernel.project_dir%/var/uploads/tus_tmp'
    tus_cache_path: '%kernel.project_dir%/var/cache/tus'
    transfer_storage_path: '%kernel.project_dir%/var/uploads/transfers'
    mailer.sender: '%env(MAILER_FROM_ADDRESS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Controller\TusController:
        arguments:
            $tusUploadPath: '%tus_upload_path%'
            $tusCachePath: '%tus_cache_path%'
        tags: ['controller.service_arguments']

    App\Service\TusUploadService:
        arguments:
            $tusCachePath: '%tus_cache_path%'
            $tusUploadPath: '%tus_upload_path%'

    App\Service\TransferManager:
        arguments:
            $transferStoragePath: '%transfer_storage_path%'

    App\MessageHandler\EmailQueueMessageHandler:
        arguments:
            $mailerSender: '%mailer.sender%'

    App\Service\TransferNotifier: ~
